# appveyor file
# http://www.appveyor.com/docs/appveyor-yml
environment:
    matrix:
        - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
        - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
        # NPM
        - NPM_VERSION: "2"
        - NPM_VERSION: "3"
        # node.js
        - NODE_VERSION: "0.12"
        - NODE_VERSION: "4"
        - NODE_VERSION: "5"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:NODE_VERSION
  - node --version
  - npm --version
  - npm install -g npm@%NPM_VERSION%
  - npm install -g jshint
  - npm install -g istanbul
  - npm install -g istanbul-coveralls
  - npm install -g nodeunit

build: off

test_script:
  - cd core
  - npm test
  - npm install . -g
  - cd ..
  - cd cli
  - npm test
  - npm install . -g
  - .\runTests
